services:
  # Spring Boot Application (Web Service)
  - type: web
    name: ecommerce-app
    runtime: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free # Sử dụng gói Free của Render
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysqlfortuna-ecommercewithtuna.j.aivencloud.com:14863/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&sessionVariables=sql_require_primary_key=OFF
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false # Bạn sẽ dán mật khẩu thật vào đây trên Render Dashboard
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: create
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.MySQLDialect
      - key: SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY
        value: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      - key: JAVA_OPTS
        value: -Xmx384m -Xms384m
      - key: SERVER_PORT
        value: 8080
